import type { Metadata } from 'next';
import { Playfair_Display } from 'next/font/google';
import './global.scss';
import Navbar from '@/components/Navbar/Navbar';
import Provider from '@/components/Provider/Provider';

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
});

export const metadata: Metadata = {
  title: 'E-commerce, Next.js',
  description: 'Generated by create next app',
};

// Layout
type PropsType = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<PropsType>) {
  return (
    <html lang="en">
      <body className={playfairDisplay.className}>
        <Provider>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
